### PR TITLE
Belarusian and Russian translations for mainline version

### PR DESCRIPTION
**Pull request by ArionWT**
Merged from transifex and added missed strings for body, marking, decoration, feet, hands and eyes.

### CODE REVIEW

**Comment by Dune-jr** [comment]
Hello,

Thanks for your contribution. We usually keep all the translation work at Transifex, and regularly export and import strings in and out of Teeworlds.

In order to export Transifex strings, we use this script: [reconvert_l10n.py](https://github.com/teeworlds/teeworlds/blob/master/scripts/reconvert_l10n.py) (which includes the old normalize.py) as described here: https://github.com/teeworlds/teeworlds-translation/wiki. It seems like your commits do not use a recent script (there is a huge diff).

The problem when you directly PR changes here is that they would get overridden by changes later over at Transifex, so it is better to keep everything there.

I will export the new strings to Transifex now so you can port those changes.

**Comment by Dune-jr** [comment]
Transifex was updated with new strings, and this repository was updated with all changes on Transifex.

**Comment by ArionWT** [comment]
Hello,
> It seems like your commits do not use a recent script (there is a huge diff).

Script was taken from [this post](https://www.teeworlds.com/forum/viewtopic.php?pid=121910#p121910). Apparently it is outdated. Thanks for the information.

> Transifex was updated with new strings

At the bottom of the files in PR were added lines that are not present on Transifex ([for example](https://imgur.com/a/EM6UOK8)). Which is strange, because after adding them, the translation is applied in the game.

**Comment by Dune-jr** [comment]
> Hello,
> 
> > It seems like your commits do not use a recent script (there is a huge diff).
> 
> Script was taken from [this post](https://www.teeworlds.com/forum/viewtopic.php?pid=121910#p121910). Apparently it is outdated. Thanks for the information.
 
Ah, sorry. I made the link stay up to date with master (it was linking a specific commit).

> > Transifex was updated with new strings
> 
> At the bottom of the files in PR were added lines that are not present on Transifex ([for example](https://imgur.com/a/EM6UOK8)). Which is strange, because after adding them, the translation is applied in the game.

So this is either an issue with the Teeworlds code (some strings are not localized in a good way), or you are using a 0.7.2 client that does not use the new strings (like the latest client from https://github.com/teeworlds/teeworlds/ does). I will test and report.

**Comment by ArionWT** [comment]
Created an issue #71, since the PR has no more sense.

**Pull request closed without merging**
