### PR TITLE
Update german.json

### PR DESCRIPTION
**Pull request by mauricepape**
Added missing translations and changed a few lines so that they sound better.

### CODE REVIEW

**Comment by Fisico** [comment]
so much better this version. Like it...

**Comment by mauricepape** [comment]
I totally forgot about this 😳 Thanks @Dune-jr for merging this!

> so much better this version. Like it...
Thank you, @Fisico :)

**Comment by Dune-jr** [comment]
@mauricepape hey :)

We have some new strings for 0.7, would you like to finish the work?

**Comment by mauricepape** [comment]
@Dune-jr 
> We have some new strings for 0.7, would you like to finish the work for german?

Sure!


> The five strings that have `"tr": ""` need to be translated:
> https://github.com/mauricepape/teeworlds-translation/blob/33e5eabb9b2a7c5a4a312b1cc82b1bb7da3a7f2d/german.json

Apologies in advance. It's been too long since I've committed something on GitHub ^^

Which one shall I translate? The german.json one from [/teeworlds/teeworlds-translation](https://github.com/teeworlds/teeworlds-translation/blob/master/german.json) doesn't have the author info and "old translations" area. Did I messed up somewhere? o.o

**Comment by Dune-jr** [comment]
It's not your fault, @mauricepape, this got merged with changes from someone else, for the 0.7 strings. You have to use https://github.com/teeworlds/teeworlds-translation/blob/master/german.json to translate indeed :)

**Comment by mauricepape** [comment]
> It's not your fault, @mauricepape, this got merged with changes from someone else, for the 0.7 strings. You have to use https://github.com/teeworlds/teeworlds-translation/blob/master/german.json to translate indeed :)
> 
> We will examine ways to restore author information for new translations. This is issue #60

I understand, @Dune-jr :)
Here's a new pull request: https://github.com/teeworlds/teeworlds-translation/pull/62

**Pull request merged**
